### ISSUE TITLE
Option to add the class set machine name as a class as well

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/classy_paragraphs#10]
It's common for there to be a common class for a set of related classes. A good example is buttons. Where a button includes classes `button-primary`, `button-secondary`, `button-danger`. But they always also have a `button` class. One way I can imagine this common class getting added is by making the class set `button` and then having it added to the classes whenever a child is chosen.

**Comment by laryn** [comment]
That could work.

**Comment by herbdool** [comment]
@laryn I've got a PR. There's a new setting per field instance to include the set name:

![2024-09-19 12 04 56 bd3 lndo site 343e7a6cd120](https://github.com/user-attachments/assets/edde7319-27ca-4d7b-ae09-084bacbab1d5)

If enabled, it will save the set name alongside the class in the db row, separated with a space, e.g. `heading heading-primary`. Then when building the content it'll fetch the value and then explode value with the space as a separator and treat each as a class to include. E.g. `class="paragraphs-item paragraphs-item-aplenty-heading paragraphs-item-aplenty-heading paragraphs-item-full paragraphs-item-1 heading heading-primary aplenty-heading"`

I figured this was a lot more efficient than looking up the set from config every time the content is rebuilt.

Since the field can only be limited to one set, it effectively just includes the selected set name, even if a class is included in multiple sets.

This is working for me.

**Comment by laryn** [comment]
@herbdool 
So in this case your set is `heading` and one of the classes is `heading-primary`? At first I thought you were suggesting to auto-concatenate sets and classes, but obviously that is not backwards-compatible without also continuing to add the non-concatenated classes, which feels like a lot of classes.

I'm trying to think whether using a space to separate them could cause any issues -- e.g. if someone has in a non-standard way entered multiple classes at once. (https://github.com/backdrop-contrib/classy_paragraphs/issues/7) But I think even that likely would continue to work, it would just split them apart, right?

**Comment by herbdool** [comment]
@laryn not sure if I quite follow the first part. My PR would be backwards-compatible so long as someone adapts their stylesheet, which they would do with any change.

As to your second point, it should be fine. The UI doesn't allow spaces but we can save them directly to the db. If someone had saved values directly with spaces then that would not be officially supported. This would display them as separate classes. And this still works if someone has multiple fields or multiple values per field.

**Comment by laryn** [comment]
It's okay if you don't understand the first part. Mostly thinking "out loud". I think this is a good improvement.

**Comment by herbdool** [comment]
Upon, rereading I understand. Yes: `heading` is the set and `heading-primary` is the class. They both get added separately.

Even though you agree this is an improvement, just one more example for the record: having classes that add background colors. If a background color is selected then it should also add padding. But the only way to reliable way to add padding in css is to have a common class that only gets applied when the color class is applied. Such as `bg-color`.

**Comment by herbdool** [comment]
I'm doing a bit of further testing just to make sure this is a good approach.

**Comment by herbdool** [comment]
I made one small change: remove duplicate classes when `classy_paragraphs_get_classes()` builds the list of classes. This is in case, a classy field allows multiple classes. Only need the set added once.

**Comment by herbdool** [comment]
I think I'm happy enough with this now.
