### ISSUE TITLE
Validation on class and set machine names.

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/classy_paragraphs#13]
It would be good to provide validation for the machine names.

**Comment by herbdool** [comment]
It's working for me @laryn.

The error message mentions "machine-readable name":

![2024-10-15 11 49 04 bd3 lndo site e78cc0442d28](https://github.com/user-attachments/assets/7a0949a7-90be-4ded-848f-652227da33ea)

so I would recommend tweaking the Class description to be something like "The class name (machine name) you wish...". The Set id already says "The ID or machine name...".

**Comment by laryn** [comment]
Thanks @herbdool!
