### ISSUE TITLE
Can't enable on last step through Project Installer

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/classy_paragraphs#4]
I was just installing this through the Project Installer on a demo site and found I couldn't enable at the last step. 

![Screen Shot 2021-03-12 at 12 38 45 PM](https://user-images.githubusercontent.com/871421/110983933-0aee7280-8330-11eb-9e00-7c5ccb5ce7fa.jpg)

However, when I continued without enabling, I could enable it from the main Modules page.

**Comment by olafgrabienski** [comment]
I guess I saw the same (but was able to enable it in the modules list).

**Comment by olafgrabienski** [comment]
This seems to be fixed in the meantime. I've just installed Classy Paragraphs and was able to enable it at the usual step. See screenshot:

![image](https://github.com/backdrop-contrib/classy_paragraphs/assets/14188307/f008a98a-4f18-49a2-9fed-2331d1727e15)

**Comment by laryn** [comment]
Thanks!
