### ISSUE TITLE
Increase size of class field

### ISSUE THREAD

**Issue by albanycomputers** [backdrop-contrib/classy_paragraphs#7]
I'd like to add a feature request to increase the Class field size from 30 characters to accommodate longer classes.

![image](https://github.com/backdrop-contrib/classy_paragraphs/assets/1705388/3ef3c562-59cd-41fc-a8c8-f5d85fc2b9e2)

I have added the animate.css CSS with CSS Injector and I want to animate the paragraphs.... but the names are quite long for example...

"animate__animated animate__fadeInUp animate__slow"
"animate__animated animate__fadeInRight animate__fast"

Many thanks.

**Comment by laryn** [comment]
@albanycomputers 

I'm not necessarily opposed, but in the specific example you gave I have a suggestion. Use three separate Classy Paragraphs fields as follows:

- Make a set for "Activation" with one class in it: "animate__animated". This field would be a checkbox to add that root level class. (You could also set up Conditional Fields to make the following two fields only show up if this box is checked).
- Make a set for "Animation type" with two (or more) classes in a dropdown/radio, for example: "animate__fadeInUp" and "animate__fadeInRight".
- Make a set for "Animation speed" with two (or more) classes in a dropdown/radio: "animate__slow" and "animate__fast"

Does that make sense?

**Comment by albanycomputers** [comment]
@laryn ahh, yes, makes perfect sense :-)

I'll have a play and report back in a few days.

Many thanks

**Comment by laryn** [comment]
Closing for now, please re-open if you would like to continue the conversation.
