### ISSUE TITLE
Unknown function classy_paragraphs_preprocess_entity() in classy_paragraphs_preprocess_edgy_paragraphs_item()

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/classy_paragraphs#9]
Why is it calling a hook directly? And why isn't it defined? And I wonder what `classy_paragraphs_preprocess_edgy_paragraphs_item()` is for.

**Comment by laryn** [comment]
Not sure about the first (I haven't looked at this code in a while) but to the second question, it can probably be dumped. I think it's related to https://www.drupal.org/project/edgy

**Comment by herbdool** [comment]
@laryn I've got a PR to remove the function which is not called.
